In [1]:
import pandas as pd

df = pd.read_csv(r"../../data/final/Load_weather_history.csv")
df.head()

df = df[df["zone_id"] == 1]

df.drop(columns=["zone_id"], inplace=True)
df.sort_values(by="time", inplace=True)
df.reset_index(drop=True, inplace=True)

df["time"] = pd.to_datetime(df["time"])
df.head()

,time,load_kw,day_of_week,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,station_9_temp_c,station_10_temp_c,station_11_temp_c
0,2004-01-01 00:00:00,16853.0,Thursday,7.777778,3.333333,6.666667,7.222222,5.555556,6.666667,7.222222,6.111111,5.000000,5.555556,2.222222
1,2004-01-01 01:00:00,16450.0,Thursday,7.777778,2.222222,5.555556,6.111111,5.555556,6.111111,6.666667,6.666667,3.888889,6.111111,0.000000
2,2004-01-01 02:00:00,16517.0,Thursday,7.222222,1.666667,4.444444,5.000000,4.444444,5.555556,5.000000,5.555556,2.222222,6.111111,-0.555556
3,2004-01-01 03:00:00,16873.0,Thursday,5.000000,-1.111111,2.222222,2.777778,3.888889,3.333333,4.444444,1.111111,1.666667,3.888889,-1.111111
4,2004-01-01 04:00:00,17064.0,Thursday,3.888889,-1.111111,1.111111,0.555556,4.444444,3.333333,1.666667,-1.111111,0.555556,1.666667,1.111111

## Feature Engineering

- Create a hour column
- create dummies for the day of the week
- create dummies for the month

In [2]:
df["hour"] = df["time"].astype("datetime64[ns]").dt.hour
df

,time,load_kw,day_of_week,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,station_9_temp_c,station_10_temp_c,station_11_temp_c,hour
0,2004-01-01 00:00:00,16853.0,Thursday,7.777778,3.333333,6.666667,7.222222,5.555556,6.666667,7.222222,6.111111,5.000000,5.555556,2.222222,0
1,2004-01-01 01:00:00,16450.0,Thursday,7.777778,2.222222,5.555556,6.111111,5.555556,6.111111,6.666667,6.666667,3.888889,6.111111,0.000000,1
2,2004-01-01 02:00:00,16517.0,Thursday,7.222222,1.666667,4.444444,5.000000,4.444444,5.555556,5.000000,5.555556,2.222222,6.111111,-0.555556,2
3,2004-01-01 03:00:00,16873.0,Thursday,5.000000,-1.111111,2.222222,2.777778,3.888889,3.333333,4.444444,1.111111,1.666667,3.888889,-1.111111,3
4,2004-01-01 04:00:00,17064.0,Thursday,3.888889,-1.111111,1.111111,0.555556,4.444444,3.333333,1.666667,-1.111111,0.555556,1.666667,1.111111,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38065,2008-06-30 01:00:00,11559.0,Monday,23.333333,18.333333,24.444444,22.222222,23.333333,21.111111,22.777778,21.666667,22.222222,21.111111,18.333333,1
38066,2008-06-30 02:00:00,11081.0,Monday,23.333333,17.777778,24.444444,22.222222,23.333333,21.111111,22.222222,21.666667,22.222222,21.111111,17.777778,2
38067,2008-06-30 03:00:00,10798.0,Monday,23.333333,17.777778,23.888889,22.222222,22.777778,21.111111,21.666667,21.666667,20.555556,21.111111,17.777778,3
38068,2008-06-30 04:00:00,10876.0,Monday,23.333333,17.777778,23.888889,22.222222,22.222222,21.111111,21.666667,21.111111,20.555556,21.111111,17.777778,4
38069,2008-06-30 05:00:00,11843.0,Monday,23.888889,17.222222,23.333333,21.666667,22.222222,20.000000,21.666667,21.666667,20.555556,21.111111,17.777778,5

In [3]:
df["month"] = df["time"].astype("datetime64[ns]").dt.month


df = pd.get_dummies(df, columns=["day_of_week"], prefix="day")
df = pd.get_dummies(df, columns=["month"], prefix="month")
df = pd.get_dummies(df, columns=["hour"], prefix="hour")

df["trend"] = range(len(df))

df.head()

# drop all columns where "station" is included in the name string

#df = df.loc[:, ~df.columns.str.contains("station")]

df

,time,load_kw,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,...,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,trend
0,2004-01-01 00:00:00,16853.0,7.777778,3.333333,6.666667,7.222222,5.555556,6.666667,7.222222,6.111111,...,False,False,False,False,False,False,False,False,False,0
1,2004-01-01 01:00:00,16450.0,7.777778,2.222222,5.555556,6.111111,5.555556,6.111111,6.666667,6.666667,...,False,False,False,False,False,False,False,False,False,1
2,2004-01-01 02:00:00,16517.0,7.222222,1.666667,4.444444,5.000000,4.444444,5.555556,5.000000,5.555556,...,False,False,False,False,False,False,False,False,False,2
3,2004-01-01 03:00:00,16873.0,5.000000,-1.111111,2.222222,2.777778,3.888889,3.333333,4.444444,1.111111,...,False,False,False,False,False,False,False,False,False,3
4,2004-01-01 04:00:00,17064.0,3.888889,-1.111111,1.111111,0.555556,4.444444,3.333333,1.666667,-1.111111,...,False,False,False,False,False,False,False,False,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38065,2008-06-30 01:00:00,11559.0,23.333333,18.333333,24.444444,22.222222,23.333333,21.111111,22.777778,21.666667,...,False,False,False,False,False,False,False,False,False,38065
38066,2008-06-30 02:00:00,11081.0,23.333333,17.777778,24.444444,22.222222,23.333333,21.111111,22.222222,21.666667,...,False,False,False,False,False,False,False,False,False,38066
38067,2008-06-30 03:00:00,10798.0,23.333333,17.777778,23.888889,22.222222,22.777778,21.111111,21.666667,21.666667,...,False,False,False,False,False,False,False,False,False,38067
38068,2008-06-30 04:00:00,10876.0,23.333333,17.777778,23.888889,22.222222,22.222222,21.111111,21.666667,21.111111,...,False,False,False,False,False,False,False,False,False,38068
38069,2008-06-30 05:00:00,11843.0,23.888889,17.222222,23.333333,21.666667,22.222222,20.000000,21.666667,21.666667,...,False,False,False,False,False,False,False,False,False,38069

In [4]:
# add 24 h offset of the load

df["load_24h"] = df["load_kw"].shift(24)
df.reset_index(drop=True, inplace=True)
df.tail()

df = df.iloc[24:]  # drop first 24 rows to avoid NaN values
df.reset_index(drop=True, inplace=True)
df

,time,load_kw,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,...,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,trend,load_24h
0,2004-01-02 00:00:00,14155.0,6.111111,7.222222,0.000000,5.555556,2.222222,7.777778,5.000000,7.222222,...,False,False,False,False,False,False,False,False,24,16853.0
1,2004-01-02 01:00:00,14038.0,6.666667,6.666667,0.555556,6.666667,2.222222,8.333333,5.555556,7.777778,...,False,False,False,False,False,False,False,False,25,16450.0
2,2004-01-02 02:00:00,14019.0,7.777778,6.666667,1.666667,7.222222,4.444444,8.333333,6.111111,7.777778,...,False,False,False,False,False,False,False,False,26,16517.0
3,2004-01-02 03:00:00,14489.0,7.777778,7.222222,3.888889,7.222222,5.555556,7.777778,7.222222,7.777778,...,False,False,False,False,False,False,False,False,27,16873.0
4,2004-01-02 04:00:00,14920.0,8.333333,7.222222,5.000000,7.777778,5.555556,8.333333,7.777778,7.777778,...,False,False,False,False,False,False,False,False,28,17064.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38041,2008-06-30 01:00:00,11559.0,23.333333,18.333333,24.444444,22.222222,23.333333,21.111111,22.777778,21.666667,...,False,False,False,False,False,False,False,False,38065,13289.0
38042,2008-06-30 02:00:00,11081.0,23.333333,17.777778,24.444444,22.222222,23.333333,21.111111,22.222222,21.666667,...,False,False,False,False,False,False,False,False,38066,12490.0
38043,2008-06-30 03:00:00,10798.0,23.333333,17.777778,23.888889,22.222222,22.777778,21.111111,21.666667,21.666667,...,False,False,False,False,False,False,False,False,38067,11612.0
38044,2008-06-30 04:00:00,10876.0,23.333333,17.777778,23.888889,22.222222,22.222222,21.111111,21.666667,21.111111,...,False,False,False,False,False,False,False,False,38068,11370.0
38045,2008-06-30 05:00:00,11843.0,23.888889,17.222222,23.333333,21.666667,22.222222,20.000000,21.666667,21.666667,...,False,False,False,False,False,False,False,False,38069,11411.0

## Split the dataset into train, validation, and test sets

- Training: first 70% of the data
- Validation: next 15% of the data
- Test: last 15% of the data
- get the index positions for the splits

In [5]:
train_start = 0
train_end = int(df.shape[0] * 0.7)

valiation_start = train_end
valiation_end = int(df.shape[0] * 0.85)

test_start = valiation_end
test_end = int(df.shape[0])

y_all =  df["load_kw"]
X_all = df.drop(columns=["load_kw", "time"])

y_train = y_all[train_start:train_end]
X_train = X_all[train_start:train_end]

y_val = y_all[train_end:valiation_end]
X_val = X_all[train_end:valiation_end]

X_test = X_all[valiation_end:test_end]
y_test = y_all[valiation_end:test_end]

y_val.head()

26632    14149.0
26633    15089.0
26634    15829.0
26635    18078.0
26636    19571.0
Name: load_kw, dtype: float64

In [6]:
len(X_test)

5707

## Train the model
- Use the training set to train the model

In [7]:
from sklearn.neural_network import MLPRegressor

model = MLPRegressor(hidden_layer_sizes=(20,5), max_iter=10000, random_state=42)
model.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(20, 5), max_iter=10000, random_state=42)

## Make predictions on all three sets

In [8]:
y_hat_train = model.predict(X_train)
y_hat_val = model.predict(X_val)
y_hat_test = model.predict(X_test)

y_hat_test[:10]

array([15991.48163108, 15463.28705357, 15038.34623312, 14901.20498396,
       15109.24493918, 15836.19327403, 17736.29631525, 19181.83559115,
       19766.53035472, 19122.56846771])

## Compute the MAPE for all three sets

In [9]:
from sklearn.metrics import mean_absolute_percentage_error

mapes = {}
for name, y_hat, y in zip(['train', 'val', 'test'], [y_hat_train, y_hat_val, y_hat_test], [y_train, y_val, y_test]):
    mape = mean_absolute_percentage_error(y, y_hat) * 100
    mapes[name] = mape
    print(f'MAPE for {name} set: {mape:.2f}')

MAPE for train set: 8.29
MAPE for val set: 9.77
MAPE for test set: 15.24

## Plot Predictions vs Actuals

- use plotly to plot the predictions vs actuals for all three sets

In [10]:
# Add the columns prediction_training, prediction_valiation, and prediction_test to the original dataframe

df["prediction_training"] = None
df["prediction_valiation"] = None
df["prediction_test"] = None
df.head()

/tmp/ipykernel_18954/3912087098.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["prediction_training"] = None
/tmp/ipykernel_18954/3912087098.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["prediction_valiation"] = None
/tmp/ipykernel_18954/3912087098.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["prediction_test"] = None

,time,load_kw,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,...,hour_19,hour_20,hour_21,hour_22,hour_23,trend,load_24h,prediction_training,prediction_valiation,prediction_test
0,2004-01-02 00:00:00,14155.0,6.111111,7.222222,0.000000,5.555556,2.222222,7.777778,5.000000,7.222222,...,False,False,False,False,False,24,16853.0,None,None,None
1,2004-01-02 01:00:00,14038.0,6.666667,6.666667,0.555556,6.666667,2.222222,8.333333,5.555556,7.777778,...,False,False,False,False,False,25,16450.0,None,None,None
2,2004-01-02 02:00:00,14019.0,7.777778,6.666667,1.666667,7.222222,4.444444,8.333333,6.111111,7.777778,...,False,False,False,False,False,26,16517.0,None,None,None
3,2004-01-02 03:00:00,14489.0,7.777778,7.222222,3.888889,7.222222,5.555556,7.777778,7.222222,7.777778,...,False,False,False,False,False,27,16873.0,None,None,None
4,2004-01-02 04:00:00,14920.0,8.333333,7.222222,5.000000,7.777778,5.555556,8.333333,7.777778,7.777778,...,False,False,False,False,False,28,17064.0,None,None,None

In [11]:
train_end-1

26631

In [12]:
# add the predictions to the original dataframe
print("length of y_hat_train", len(y_hat_train))
print("length of y_hat_val", len(y_hat_val))
print("length of y_hat_test", len(y_hat_test))

df.loc[0:train_end-1, "prediction_training"] = y_hat_train
df.loc[train_end:valiation_end-1, "prediction_valiation"] = y_hat_val
df.loc[valiation_end:test_end, "prediction_test"] = y_hat_test

df.head()

length of y_hat_train 26632
length of y_hat_val 5707
length of y_hat_test 5707

,time,load_kw,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,...,hour_19,hour_20,hour_21,hour_22,hour_23,trend,load_24h,prediction_training,prediction_valiation,prediction_test
0,2004-01-02 00:00:00,14155.0,6.111111,7.222222,0.000000,5.555556,2.222222,7.777778,5.000000,7.222222,...,False,False,False,False,False,24,16853.0,12852.308352,None,None
1,2004-01-02 01:00:00,14038.0,6.666667,6.666667,0.555556,6.666667,2.222222,8.333333,5.555556,7.777778,...,False,False,False,False,False,25,16450.0,12679.950654,None,None
2,2004-01-02 02:00:00,14019.0,7.777778,6.666667,1.666667,7.222222,4.444444,8.333333,6.111111,7.777778,...,False,False,False,False,False,26,16517.0,12870.560977,None,None
3,2004-01-02 03:00:00,14489.0,7.777778,7.222222,3.888889,7.222222,5.555556,7.777778,7.222222,7.777778,...,False,False,False,False,False,27,16873.0,12585.521625,None,None
4,2004-01-02 04:00:00,14920.0,8.333333,7.222222,5.000000,7.777778,5.555556,8.333333,7.777778,7.777778,...,False,False,False,False,False,28,17064.0,12909.59396,None,None

In [13]:
import plotly.graph_objects as go
# sort the dataframe by time
df.sort_values(by="time", inplace=True)
df.reset_index(drop=True, inplace=True)
df["time"] = pd.to_datetime(df["time"])

fig = go.Figure()
fig.add_trace(go.Scatter(x=df["time"], y=df["load_kw"], mode='lines', name='Load'))
fig.add_trace(go.Scatter(x=df["time"][train_start:train_end], y=df["prediction_training"][train_start:train_end], mode='lines', name='Prediction Train'))
fig.add_trace(go.Scatter(x=df["time"][train_end:valiation_end], y=df["prediction_valiation"][train_end:valiation_end], mode='lines', name='Prediction Validation'))
fig.add_trace(go.Scatter(x=df["time"][valiation_end:test_end], y=df["prediction_test"][valiation_end:test_end], mode='lines', name='Prediction Test'))

fig.show()

/tmp/ipykernel_18954/2503885314.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by="time", inplace=True)
/tmp/ipykernel_18954/2503885314.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["time"] = pd.to_datetime(df["time"])

In [14]:
df

,time,load_kw,station_1_temp_c,station_2_temp_c,station_3_temp_c,station_4_temp_c,station_5_temp_c,station_6_temp_c,station_7_temp_c,station_8_temp_c,...,hour_19,hour_20,hour_21,hour_22,hour_23,trend,load_24h,prediction_training,prediction_valiation,prediction_test
0,2004-01-02 00:00:00,14155.0,6.111111,7.222222,0.000000,5.555556,2.222222,7.777778,5.000000,7.222222,...,False,False,False,False,False,24,16853.0,12852.308352,None,None
1,2004-01-02 01:00:00,14038.0,6.666667,6.666667,0.555556,6.666667,2.222222,8.333333,5.555556,7.777778,...,False,False,False,False,False,25,16450.0,12679.950654,None,None
2,2004-01-02 02:00:00,14019.0,7.777778,6.666667,1.666667,7.222222,4.444444,8.333333,6.111111,7.777778,...,False,False,False,False,False,26,16517.0,12870.560977,None,None
3,2004-01-02 03:00:00,14489.0,7.777778,7.222222,3.888889,7.222222,5.555556,7.777778,7.222222,7.777778,...,False,False,False,False,False,27,16873.0,12585.521625,None,None
4,2004-01-02 04:00:00,14920.0,8.333333,7.222222,5.000000,7.777778,5.555556,8.333333,7.777778,7.777778,...,False,False,False,False,False,28,17064.0,12909.59396,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38041,2008-06-30 01:00:00,11559.0,23.333333,18.333333,24.444444,22.222222,23.333333,21.111111,22.777778,21.666667,...,False,False,False,False,False,38065,13289.0,None,None,17948.659162
38042,2008-06-30 02:00:00,11081.0,23.333333,17.777778,24.444444,22.222222,23.333333,21.111111,22.222222,21.666667,...,False,False,False,False,False,38066,12490.0,None,None,18348.658412
38043,2008-06-30 03:00:00,10798.0,23.333333,17.777778,23.888889,22.222222,22.777778,21.111111,21.666667,21.666667,...,False,False,False,False,False,38067,11612.0,None,None,18920.878024
38044,2008-06-30 04:00:00,10876.0,23.333333,17.777778,23.888889,22.222222,22.222222,21.111111,21.666667,21.111111,...,False,False,False,False,False,38068,11370.0,None,None,19184.537704
38045,2008-06-30 05:00:00,11843.0,23.888889,17.222222,23.333333,21.666667,22.222222,20.000000,21.666667,21.666667,...,False,False,False,False,False,38069,11411.0,None,None,19328.560174

In [15]:
# print error by weekday as violin plot

df["error_training"] = df["load_kw"] - df["prediction_training"]
df["error_valiation"] = df["load_kw"] - df["prediction_valiation"]
df["error_test"] = df["load_kw"] - df["prediction_test"]
import plotly.express as px

df["day_of_week"] = df["time"].dt.dayofweek
df["day_of_week_0"] = df["day_of_week"].astype(str)
df["day_of_week_0"] = df["day_of_week_0"].replace({
    '0': 'Monday',
    '1': 'Tuesday',
    '2': 'Wednesday',
    '3': 'Thursday',
    '4': 'Friday',
    '5': 'Saturday',
    '6': 'Sunday'
})
fig = px.violin(df, y="error_training", x="day_of_week_0", color="day_of_week_0", box=True, title="Error by Day of Week (Training)")

fig.show()

/tmp/ipykernel_18954/2556996959.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18954/2556996959.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18954/2556996959.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18954/2556996959.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18954/2556996959.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18954/2556996959.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

## Auffälligkeiten

- Sprünge zwischen den Monaten (Unterschiedliche Niveaus durch die Faktoren der Dummy Variablen)
- Saisonalität wird abgebildet
- Spitzen in den Daten werden nicht gut abgebildet

In [16]:
# plot distribution of forecasts fs real values

import plotly.express as px
fig = px.histogram(df, x="load_kw", nbins=100, title="Distribution of Real Load Values")
fig.add_trace(px.histogram(df, x="prediction_training", nbins=100).data[0])
#fig.add_trace(px.histogram(df, x="prediction_valiation", nbins=100).data[0])
#fig.add_trace(px.histogram(df, x="prediction_test", nbins=100).data[0])
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=0.75)
fig.show()